name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - dev
      - feat/*
      - chore/*
  push:
    branches:
      - main
      - dev
      - feat/*
      - chore/*

permissions:
  contents: read

jobs:
  build-action:
    name: Build Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Build
        id: npm-all
        run: npm run all

  # # I don't know how to test.
  # test-action:
  #   name: Test Action
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       id: checkout
  #       uses: actions/checkout@v4

  #     - name: Test Local Action
  #       id: test-action
  #       uses: ./
  #       with:
  #         repo-token: "${{ secrets.GITHUB_TOKEN }}"
  #         configuration-path: .github/issue-checker.yml
  #         not-before: 2022-08-05T00:00:00Z
  #         include-title: 1
